name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGENAME: bonbonn-game-tracker
      CONTAINER: bonbonn-gt
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.password }}
        port: 22
          
        script: |
          docker image list
          docker ps
          docker stop ${{ env.CONTAINER }} -f
          docker rm ${{ env.CONTAINER }} -f
          docker rmi ${{ env.IMAGENAME }} -f
          echo ----------------------------------------------------
          docker image list
          docker ps
          echo ----------------------------------------------------
          cd /home/bonbonn-game-tracker
          git pull
          docker build -t ${{ env.IMAGENAME }} .
          #docker start ${{ env.IMAGENAME }}
          docker run --restart=always -d --name ${{ env.CONTAINER }} -p 127:0.0.1:12000:12000 ${{ env.IMAGENAME }}
